/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: FUD-UJEP (https://sketchfab.com/FUD-UJEP)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/la-night-city-a85450184c6e4ddf87b49c402641e5b4
Title: LA Night City
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.124}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0.geometry}
              material={materials.Dtla_Orbit_u3_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0_1.geometry}
              material={materials.Dtla_Orbit_u3_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0_2.geometry}
              material={materials.Dtla_Orbit_u3_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0_3.geometry}
              material={materials.Dtla_Orbit_u3_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0.geometry}
              material={materials.Dtla_Orbit_u1_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0_1.geometry}
              material={materials.Dtla_Orbit_u1_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0_2.geometry}
              material={materials.Dtla_Orbit_u1_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0.geometry}
              material={materials.Dtla_Orbit_u2_v2}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0_1.geometry}
              material={materials.Dtla_Orbit_u2_v2}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0_2.geometry}
              material={materials.Dtla_Orbit_u2_v2}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0_3.geometry}
              material={materials.Dtla_Orbit_u2_v2}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0.geometry}
              material={materials.Dtla_Orbit_u2_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0_1.geometry}
              material={materials.Dtla_Orbit_u2_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0_2.geometry}
              material={materials.Dtla_Orbit_u2_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0_3.geometry}
              material={materials.Dtla_Orbit_u2_v1}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0.geometry}
              material={materials.Dtla_Orbit_u1_v2}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0_1.geometry}
              material={materials.Dtla_Orbit_u1_v2}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0_2.geometry}
              material={materials.Dtla_Orbit_u1_v2}
            />
            <mesh
              geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0_3.geometry}
              material={materials.Dtla_Orbit_u1_v2}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
